apiVersion: v1
kind: Pod
metadata:
  name: "{{.Release.Name}}-pod"
spec:
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
  containers:
  - name: alpine
    image: alpine:3.4
    command: ["echo", "hello $(username) $(password)"]
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: {{.Release.Name}}-secret
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: {{.Release.Name}}-secret
          key: password
