apiVersion: v1
kind: Secret
metadata:
  name: "{{.Release.Name}}-secret"
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  password: {{ b64enc (randAlpha 32) }}
  username: {{ b64enc "user1" }}
