apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx:1.11
    ports:
    - containerPort: 80
  - name: alpine
    image: alpine:3.4
    # command: ["wget", "localhost"]
    command: ["watch", "wget", "-qO-", "localhost"]